import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  {
    // Generated/vendored code and build output are not ours to lint.
    // client/src/components/ui/** and the two use-* hooks are shadcn-generated
    // and are regenerated by the CLI — linting them just creates churn.
    ignores: [
      "dist/**",
      "node_modules/**",
      "client/src/components/ui/**",
      "client/src/hooks/use-toast.ts",
      "client/src/hooks/use-mobile.tsx",
      "data.db*",
      "coverage/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parserOptions: { ecmaVersion: "latest", sourceType: "module" },
    },
    rules: {
      // Surface `any` as a warning: there's a known backlog of them (Phase 1
      // tames the worst), but new ones shouldn't fail the build silently.
      "@typescript-eslint/no-explicit-any": "warn",
      // Allow intentionally-unused args when prefixed with _ (common in Express
      // middleware signatures like (_req, res, next)).
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-empty": ["error", { allowEmptyCatch: true }],
    },
  },
  {
    files: ["client/src/**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: reactHooks.configs.recommended.rules,
  },
  {
    // Config files legitimately use require() for plugin loading.
    files: ["*.config.{ts,js}"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
  {
    // Tests use `any` deliberately: mock shapes, partial fixtures, and probing
    // malformed input. Enforcing it here produces noise, not safety — and the
    // noise was drowning out the handful of real ones in production code.
    files: ["**/*.test.ts", "**/*.test.tsx"],
    rules: { "@typescript-eslint/no-explicit-any": "off" },
  },
  prettier // must stay last: disables stylistic rules Prettier owns
);
