/**
 * Schema migrations.
 *
 * Replaces the old `addColumnIfMissing` calls that mutated the schema on every
 * boot: they were unversioned, silent on failure, and had no way to express
 * anything but "add a nullable column".
 *
 * Migrations live in ./migrations (generated by `npm run db:generate`) and are
 * applied here at startup. The 0000 baseline is written with IF NOT EXISTS so
 * databases created before migrations existed adopt cleanly; later migrations
 * are ordinary.
 */
import type BetterSqlite3 from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import { log } from "./logger";

const logger = log("migrate");

export function runMigrations(sqlite: BetterSqlite3.Database): void {
  const db = drizzle(sqlite);
  try {
    migrate(db, { migrationsFolder: "./migrations" });
    logger.info("schema up to date");
  } catch (e) {
    // A failed migration means the schema is in an unknown state — refuse to
    // serve rather than limping along and corrupting data.
    logger.error({ err: e }, "migration failed");
    throw e;
  }
}
